### ISSUE TITLE
libstdc++-6.dll

### ISSUE THREAD

**Issue by mio12333** [garfeng/keyboard#3]
---------------------------
keyboard.exe - 系統錯誤
---------------------------
程式碼執行無法繼續，因為找不到 libstdc++-6.dll。重新安裝程式或許可以修正此問題。 
---------------------------
確定   
---------------------------

**Comment by pfugwtg** [comment]
可以修改 Makefile 文件指令：
`go build -ldflags "-w -s -H windowsgui -extldflags --static"`
